# Generated by Django 4.1.5 on 2023-05-02 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_unit_price_product_unit_aprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='unit_aprice',
            new_name='unit_price',
        ),
    ]
